# .github/workflows/publish.yml

name: Publish Alpha
on:
  push:
    branches: [ main ]
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Detect changes in build-logic
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            buildlogic:
              - 'build-logic/**'
              - 'gradle-plugin/**'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Publish Gradle Plugin Skipped, Cause No changes in build-logic
        if: steps.changes.outputs.buildlogic != 'true'
        run: echo "No changes detected in build-logic — skipping publish"
      - name: Publish Gradle Plugin
        if: steps.changes.outputs.buildlogic == 'true'
        run: ./gradlew :build-logic:convention:publishPlugins -Pproject.build_number=alpha.${{ github.run_number }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Publish to MavenCentral
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache -Pproject.build_number=alpha.${{ github.run_number }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
